---
# sourcecodester parser setup
# convert to json using https://www.json2yaml.com/

# directories to save logs
#   - src/scraper-output/01-ProjectListPage
#   - src/scraper-output/02-ProjectSourcesDownloadLink
#   - src/scraper-output/03-ProjectSourcesZipFile  

# parser has the following components
#   - 01-ProjectListPage
#   - 02-ProjectSourcesDownloadLink
#   - 03-ProjectSourcesZipFile

SiteUrl: "https://www.sourcecodester.com/"

# 01-ProjectListPage
ProjectListPage:
  MakeRequestsToNetwork: true
  PaginationStartPage: 1
  PaginationEndPage: 10

# 02-ProjectSourcesDownloadLink
ProjectSourcesDownloadLink:
  MakeRequestsToNetwork: false
  PaginationStartPage: 1
  PaginationEndPage: 10

# 03-ProjectSourcesZipFile
ProjectSourcesZipFile:
  MakeRequestsToNetwork: false
  PaginationStartPage: 1
  PaginationEndPage: 10